In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
datasets = pd.read_csv('./data/iris.data', names=names)
datasets.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [23]:
datasets.Class.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [2]:
datasets.tail()

sepal-length  sepal-width  petal-length  petal-width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [6]:
x = datasets.iloc[:, :-1].values
y = datasets.iloc[:,4].values
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
from sklearn.model_selection import train_test_split

#train_set, test_set 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [14]:
from sklearn.preprocessing import StandardScaler

#데이터를 평균이 0, 표준편차 1이 되도록 변환(각 데이터셋의 크기가 뒤죽박죽인 경우 많기 때문)
s = StandardScaler()
x_train = s.fit_transform(x_train)
x_test = s.fit_transform(x_test)
print(x_train[:5], x_test[:5])

[[ 0.80099844  0.28031429  0.77854524  1.04528238]
 [-0.26305853 -0.18365419  0.22144668  0.14841088]
 [ 1.6285983  -0.18365419  1.16851423  0.53278438]
 [-1.44534405  0.04833005 -1.22700958 -1.26095862]
 [-0.73597274  0.74428277 -1.28271944 -1.26095862]] [[ 0.37359279 -0.36361648  0.51540128  0.80834839]
 [-1.12989038  2.00779536 -1.56724064 -1.42328827]
 [ 0.78363365 -0.36361648  0.38918056  0.36202106]
 [ 0.2369125   0.11066589  0.38918056  0.21324528]
 [ 1.05699423  0.82208944  1.08339454  1.25467572]]


In [15]:
from sklearn.neighbors import KNeighborsClassifier

#k=50개로 분류
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [16]:
from sklearn.metrics import accuracy_score

y_pred = knn.predict(x_test)
print(f"정확도: {accuracy_score(y_test, y_pred)}")

정확도: 0.8666666666666667


In [24]:
#최적의 k 찾기
k = 100
acc_array = np.zeros(k)

for k in np.arange(1, k+1, 1): #1부터 k까지 값을 취함
    classifier = KNeighborsClassifier(n_neighbors=k).fit(x_train, y_train)
    y_pred = classifier.predict(x_test) #x_test 데이터로 y값 예측
    acc = metrics.accuracy_score(y_test, y_pred) #y_test값과 y_pred값으로 정확도 산출
    acc_array[k-1] = acc #acc_array에 for문 번호에 해당하는 acc값 입력
    
max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc) #최고 정확도 나온 값을 최적의 k로 함
print(acc_list)
print(k)
print("정확도", max_acc, "으로 최적의 k는", k+1, "입니다")

[0.9666666666666667, 0.9333333333333333, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9333333333333333, 0.9666666666666667, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9, 0.9, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8666666666666667, 0.8333333333333334, 0.8666666666666667, 0.8333333333333334, 0.8666666666666667, 0.83